### PR TITLE
[draft] React callbacks

### PR DESCRIPTION
**Pull request by atherdon**

### CODE REVIEW

**Comment by atherdon** [comment]
https://user-images.githubusercontent.com/1469198/180610614-eeb229fb-1013-4e48-9c50-fbedf7c60b02.mp4

сс @vadim9999

**Comment by vadim9999** [comment]
@atherdon which module to use for typography?

**Comment by vadim9999** [comment]
@atherdon can we merge this PR?

**Comment by atherdon** [comment]
we need to fix merge conflics, but yeah, i think we can merge it if plain generator working

**Comment by atherdon** [comment]
Just published an update at 
image

now we can pass whole config into our components

**Pull request merged**
